name: 'Lock inactive issues and PRs'

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  issues: write

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: klaasnicolaas/action-inactivity-lock@v1
        with:
          days-inactive-issues: 1
          issue-comment:  >
            This issue has been closed for over 7 days.
            Feel free to open a new one and reference this if needed.
      - name: ğŸ” Display locked issues
        run: |
          echo "Locked issues: $(echo '${{ steps.lock.outputs.locked-issues }}' | jq)"